dns1: "8.8.8.8"
dns2: "8.8.4.4"
ipv4_address: "192.168.6.1/24"
ipv4_ranges: "192.168.6.10-192.168.6.250"

incus_hosts:
  - name: sys-deb12-dev6
    os: debian12-packer
  - name: sys-alma9-dev6
    os: alma9-packer
  - name: sys-deb13-dev6
    os: debian13-packer
  - name: sys-ubu22-dev6
    os: ubu22-packer
  - name: sys-ubu24-dev6
    os: ubu24-packer
