---
puppet_bolt_link:
  Debian: "https://apt.puppet.com/puppet-release-bookworm.deb"
  RedHat: "https://yum.puppet.com/puppet-release-el-9.noarch.rpm"
  Ubuntu: "https://apt.puppet.com/puppet-release-jammy.deb"
  Suse: "https://yum.puppet.com/puppet-release-sles-15.noarch.rpm"
